import ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean.PatientPresentation
import ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean.BayesianInference
import ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean.CompartmentModel
import ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean.SurvivalAnalysis
import ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean.DiagnosticTest
import ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean.DiagnosisRoute

namespace HautevilleHouse
namespace ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean

end ClinicalMedicineDiagnosisTheoryFoundationCanonicalLaneLean
end HautevilleHouse